train_dataset: ???
validation_dataset: ???

training_ds:
  dataset:
    _target_: "nemo.collections.tts.data.datalayers.MelAudioDataset"
    manifest_filepath: ${train_dataset}
    min_duration: 0.75
    n_segments: 16384
    mel_hop_size: 256
  dataloader_params:
    drop_last: false
    shuffle: true
    batch_size: 16
    num_workers: 4

validation_ds:
  dataset:
    _target_: "nemo.collections.tts.data.datalayers.MelAudioDataset"
    manifest_filepath: ${validation_dataset}
    min_duration: 0.75
    n_segments: 16384
    mel_hop_size: 256
  dataloader_params:
    drop_last: false
    shuffle: false
    batch_size: 2
    num_workers: 1

optim:
  _target_: torch.optim.AdamW
  lr: 0.0001
  betas: [0.8, 0.99]