# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.
# TLT spec file for training the Jasper model for TTS using the Mozilla Common Voice English dataset.

sample_rate: 22050
train_dataset: ???
validation_dataset: ???
prior_folder: ???

n_speakers: ???
n_window_size: 1024
n_window_stride: 256
pitch_fmin: ???
pitch_fmax: ???
pitch_avg: ???
pitch_std: ???

train_ds:
  dataset:
    _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharWithPriorAndPitchDataset"
    manifest_filepath: ${train_dataset}
    max_duration: null
    min_duration: 0.1
    int_values: false
    normalize: true
    sample_rate: ${sample_rate}
    trim: false
    sup_data_path: ${prior_folder}
    n_window_stride: ${n_window_stride}
    n_window_size: ${n_window_size}
    pitch_fmin: ${pitch_fmin}
    pitch_fmax: ${pitch_fmax}
    pitch_avg: ${pitch_avg}
    pitch_std: ${pitch_std}
    vocab:
      notation: phonemes
      punct: true
      spaces: true
      stresses: true
      add_blank_at: None
      pad_with_space: True
      chars: true
      improved_version_g2p: true
  dataloader_params:
    drop_last: false
    shuffle: true
    batch_size: 32
    num_workers: 12

validation_ds:
  dataset:
    _target_: "nemo.collections.asr.data.audio_to_text.AudioToCharWithPriorAndPitchDataset"
    manifest_filepath: ${validation_dataset}
    max_duration: null
    min_duration: null
    int_values: false
    normalize: true
    sample_rate: ${sample_rate}
    trim: false
    sup_data_path: ${prior_folder}
    n_window_stride: ${n_window_stride}
    n_window_size: ${n_window_size}
    pitch_fmin: ${pitch_fmin}
    pitch_fmax: ${pitch_fmax}
    pitch_avg: ${pitch_avg}
    pitch_std: ${pitch_std}
    vocab:
      notation: phonemes
      punct: true
      spaces: true
      stresses: true
      add_blank_at: None
      pad_with_space: True
      chars: true
      improved_version_g2p: true
  dataloader_params:
    drop_last: false
    shuffle: false
    batch_size: 32
    num_workers: 8

optim:
  name: adam
  lr: 2e-4
  betas: [0.9, 0.98]
  weight_decay: 1e-6